#!/bin/bash

#
# chkconfig: - 50 50
# description: Tinytrapd SNMP Trap Daemon
#
. /etc/init.d/functions

OPTIONS="-c /etc/tinytrapd/tinytrapd.conf"
RETVAL=0
prog="tinytrapd"

start() {
	echo -n $"Starting $prog: "
        /usr/bin/$prog $OPTIONS
	RETVAL=$?
	echo
	touch /var/lock/subsys/$prog
	return $RETVAL
}

stop() {
	echo -n $"Stopping $prog: "
	killproc /usr/sbin/$prog
	RETVAL=$?
	echo
	rm -f /var/lock/subsys/$prog
	return $RETVAL
}

reload(){
	stop
	start
}

restart(){
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	restart
        ;;
  reload)
	reload
        ;;
  status)
        status $prog
	RETVAL=$?
        ;;
  *)
	echo $"Usage: $0 {start|stop|status|restart|reload}"
	RETVAL=1
esac

exit $RETVAL
